name: sendit-email-assistant-ci

on:
    push:
      branches:
        - main
      paths:
        - 'email-assistant/**'
    pull_request:
      branches:
        - main
      paths:
        - 'email-assistant/**'

env:
  APP_ROOT_PATH: ./email-assistant

jobs:
  Verify:
    runs-on: ubuntu-24.04

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Verify: Go Mod"
        run: cd $APP_ROOT_PATH && go mod verify

  Lints:
    runs-on: ubuntu-24.04
    needs: Verify

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Setup: Install staticcheck"
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: "Setup: Install Golint"
        run: go install golang.org/x/lint/golint@latest
    
      - name: "Step: Go Vet"
        run: cd $APP_ROOT_PATH && go vet ./...

      - name: "Step: Golint"
        run: cd $APP_ROOT_PATH && golint ./...

      - name: "Step:Staticcheck"
        run: cd $APP_ROOT_PATH && staticcheck ./...

  Build:
    runs-on: ubuntu-24.04
    needs: Lints

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Step: Build"
        run: cd $APP_ROOT_PATH && go build -v ./...
