name: web-app-cd

on:
  push:
    branches:
      - main
    paths:
      - 'web-app/**'
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4
      - name: "Setup: GitHub Pages"
        uses: actions/configure-pages@v5
      - name: "Setup: Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: "Setup: Inject environment variables"
        run: |
          echo "APLICATION_URL=${{ secrets.APLICATION_URL }}" >> .env
      - name: "Upload: Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web-app'
      - name: "Deploy: GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
